import { Content } from "@/april28_23/components/layout/layout";
import { Card } from "@/april28_23/domainComponents/card/card";
import { Slider } from "@/april28_23/domainComponents/slider/slider";
import Head from "next/head";
import { useRouter } from "next/router";

/**
 * <><><> April 28th Practice Session - LESSONS LEARNED <><><>
 *
 * WINS:
 * TailwindCSS is neat, can replace our use of Bootstrap for quick utility classes
 * Planning first pays off always, having a rough idea of component breakdown ahead of time
 * Got most of the mock re-created + the whole tailwind / project setup in about 1.5 - 1.75 hours, that's neat
 * Proficiency with NextJS is increasing quickly
 * Project directory structure seems pretty clean.
 *
 *
 * LOSSES:
 * Still a little rushed and dependent on constantly seeing the finished rendered thing to iterate
 * Next time should try and allocate more time to refactoring and doing best practices
 *  Perhaps next practice session should revisit this mock and cleanup the code, add animation, etc
 *
 * Things to Learn More:
 * Balance between dedicated, heavier Styled Components vs. quick and easy utility class components from Tailwind
 * Would have been cool to animate the slider across with React Spring and react-use-gesture (ran out of time)
 * SSR for Tailwindd CSS seems to not be currently working https://github.com/vercel/next.js/issues/38561
 *
 *
 */

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Unplug</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </Head>
      <Content>
        <div>
          <div className="flex items-center justify-between w-full my-4">
            <span className="text-white" onClick={() => router.back()}>
              Back
            </span>
            <a className="text-white" href="https://dribbble.com/shots/21320120-Banking-App">
              Dribble
            </a>
          </div>
          <Card
            displayType="secondary"
            mask={4765111122225674}
            expiration={"03/25"}
            balance={3201.34}
            cardType={"mastercard"}
            bankName={"World Bank"}
          />
          <Card
            displayType="primary"
            mask={3456111122222234}
            expiration={"04/28"}
            balance={2156.09}
            cardType={"visa"}
            bankName={"Country Bank"}
          />
        </div>
        <Slider />
      </Content>
    </>
  );
}
