import {
  Content,
  ImageContainer,
  IntroPage,
  LastPage,
  Page,
  SmallerImageContainer,
} from "@/components/layout/layout";
import { Comfortaa } from "next/font/google";
import Head from "next/head";
import Image from "next/image";

import autoReplyImage from "./autoreply.png";
import drivingImage from "./driving.png";
import focusImage from "./focus.png";
import messageImage from "./message.png";
import settingsIcon from "./settings-icon.png";

import drivingState from "./driving.jpg";
import focusState from "./focus-state.jpg";

import logo from "./logo.png";

const stepIconSize = 32;

import { StyledText } from "@/components/typography/typography";
import {
  faArrowRight,
  faCircleArrowDown,
  faPlug,
  faSquareCheck,
  faTree,
} from "@fortawesome/pro-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import confetti from "canvas-confetti";
import Script from "next/script";

const ComfortaaFont = Comfortaa({ subsets: ["latin"], variable: "--comfortaa-font" });

export const PageBottomIcon: React.FC<{ color: string }> = ({ color }) => {
  return (
    <FontAwesomeIcon
      className="mr-2 fa-fade absolute"
      icon={faCircleArrowDown}
      onClick={() => {
        const el = document.getElementById("content");
        const pos = el!.getBoundingClientRect();
        const page2 = document.getElementById("page2");
        console.log({ el, pos, page2 });
        page2!.scrollTo(0, pos.top);
        // window.scrollBy({
        //   top: window.innerHeight,
        //   behavior: "smooth",
        // );
      }}
      style={{
        bottom: "84px",
      }}
      color={color}
      size="3x"
    />
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Unplug</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </Head>
      <Content id="content">
        <IntroPage className="justify-end flex">
          <ImageContainer>
            <Image priority src="/unplug.png" alt={""} width={0} height={0} sizes="100vw" />
          </ImageContainer>
          <p
            className={`${ComfortaaFont.className} text-2xl md:text-4xl text-center `}
            style={{ color: "#B59D5F", marginTop: "1rem" }}
          >
            A social movement of unplugging from technology responsibly.
            {/* Regain your time back one <b>unplugged</b> day at a time. */}
          </p>

          <hr
            className="my-4"
            style={{ height: "4px", borderTopColor: "#8B5C004D", width: "100%" }}
          />
          <div
            style={{
              color: "#B49C61",
              fontWeight: 800,
              margin: "0 auto",
            }}
            className={`${ComfortaaFont.className} flex flex-col items-center text-sm md:text-md my-1 w-full md:w-2/3 `}
          >
            <p
              className={`${ComfortaaFont.className} text-base md:text-lg `}
              style={{ color: "#B59D5F" }}
            >
              We&apos;re happier off our phones.
              {/* Regain your time back one <b>unplugged</b> day at a time. */}
            </p>
            <p
              className={`${ComfortaaFont.className} text-base md:text-lg `}
              style={{ color: "#B59D5F" }}
            >
              Yet we live in a connected world.
              {/* Regain your time back one <b>unplugged</b> day at a time. */}
            </p>
            <p
              className={`${ComfortaaFont.className} text-base md:text-lg `}
              style={{ color: "#B59D5F" }}
            >
              We found a solve.
            </p>
          </div>

          <PageBottomIcon color="#B49C61" />
        </IntroPage>
        <IntroPage id="page2" style={{ justifyContent: "space-between", paddingBottom: 0 }}>
          <Script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.5.1/dist/confetti.browser.min.js"></Script>
          <div
            style={{
              color: "#B49C61",
              fontWeight: 800,
              margin: "0 auto",
            }}
            className={`${ComfortaaFont.className} text-sm md:text-xl my-1 w-full md:w-2/3 `}
          >
            <p className="my-3">
              <FontAwesomeIcon className="mr-2" icon={faSquareCheck} color="#B49C61" size="1x" />
              Setup an auto-reply message (on iOS)
            </p>
            <div className="flex items-center justify-center w-full">
              <div className="flex flex-col items-center">
                <Image
                  priority
                  src={settingsIcon}
                  alt={""}
                  width={stepIconSize}
                  height={stepIconSize}
                />
                <p
                  className={`${ComfortaaFont.className} text-xs md:text-md my-1 `}
                  style={{ color: "#91928F" }}
                >
                  Settings
                </p>
              </div>
              <FontAwesomeIcon className="mx-1" icon={faArrowRight} color="#B49C61" size="2x" />
              <div className="flex flex-col items-center">
                <Image
                  priority
                  src={focusImage}
                  alt={""}
                  width={stepIconSize}
                  height={stepIconSize}
                />
                <p
                  className={`${ComfortaaFont.className} font-bold text-xs md:text-md my-1 `}
                  style={{ color: "#575ACE" }}
                >
                  Focus
                </p>
              </div>
              <FontAwesomeIcon className="mx-2" icon={faArrowRight} color="#B49C61" size="2x" />

              <div className="flex flex-col items-center">
                <Image
                  priority
                  src={drivingImage}
                  alt={""}
                  width={stepIconSize}
                  height={stepIconSize}
                />
                <p
                  className={`${ComfortaaFont.className} text-xs md:text-md my-1 `}
                  style={{ color: "#33379D" }}
                >
                  Driving
                </p>
              </div>
              <FontAwesomeIcon className="mx-1" icon={faArrowRight} color="#B49C61" size="2x" />
              <Image priority src={autoReplyImage} alt={""} width={94} height={32} />
            </div>

            <SmallerImageContainer className="my-2">
              <Image
                priority
                placeholder="blur"
                src={messageImage}
                alt={""}
                width={0}
                height={0}
                sizes="100vw"
              />
            </SmallerImageContainer>

            <p className="text-center my-1">
              <u
                onClick={async () => {
                  if (typeof window !== undefined) {
                    window.navigator.clipboard.writeText(
                      `Hi! You’ve reached me on an Unplugged day. I’m most likely enjoying the outdoors, reading in a coffee shop, or simply taking a break from technology. Feel free to call, I’d love to chat and will pick up, otherwise I won’t see your text until tomorrow and will get back to you then. Thanks! 😎 If you’re curious about what an Unplugged day is checkout https://www.unplug.club`
                    );
                    confetti({
                      colors: ["#B49C61"],
                    });
                  }
                }}
              >
                Click here to copy the above
              </u>
            </p>
            <p className="my-3">
              <FontAwesomeIcon className="mr-2" icon={faSquareCheck} color="#B49C61" size="1x" />
              Enable Driving Mode
            </p>
            <div className="flex items-center justify-around w-full">
              <Image priority src={focusState} alt={""} width={80} height={stepIconSize} />
              <Image priority src={drivingState} alt={""} width={120} height={stepIconSize} />
            </div>

            <p className="my-3">
              <FontAwesomeIcon className="mr-2" icon={faSquareCheck} color="#B49C61" size="1x" />
              Lock your screen & ignore for 36 hours
            </p>
          </div>

          <PageBottomIcon color="#B49C61" />
        </IntroPage>
        <Page>
          <div className="flex items-center flex-col w-full">
            <p
              className={`${ComfortaaFont.className} text-3xl md:text-6xl my-6 `}
              style={{
                color: "#F6F1E0",
                fontWeight: 800,
              }}
            >
              Unplugged =
            </p>

            <div className="flex items-start justify-between flex-row w-full">
              <div className="flex items-start flex-col">
                <p
                  className={`${ComfortaaFont.className} text-xl md:text-3xl `}
                  style={{
                    color: "#F6F1E0",
                    fontWeight: 800,
                  }}
                >
                  <u>Not Allowed</u> <FontAwesomeIcon icon={faPlug} color="#F5EFDB" size="1x" />
                </p>
                <div
                  className={`${ComfortaaFont.className} text-md md:text-xl mt-1 `}
                  style={{
                    color: "#F6F1E0",
                    fontWeight: 800,
                  }}
                >
                  <p>- No TV</p>
                  <p>- No phone</p>
                  <p>- No computer</p>
                  <p>- No smart watch</p>
                  <p>- No social media</p>
                  <p>- No news</p>
                  <p>- No friends TV</p>
                  <p>- No meetings</p>
                  <p>- No work</p>
                  <p>- No email</p>
                  <p>- No video games</p>
                  <p>- No navigation</p>
                  <p>- No scrolling</p>
                  <p>- No screens</p>
                  <p>- No texting</p>
                </div>
              </div>
              <div className="flex items-start flex-col">
                <p
                  className={`${ComfortaaFont.className} text-xl md:text-3xl `}
                  style={{
                    color: "black",
                    fontWeight: 800,
                  }}
                >
                  <u>Allowed</u> <FontAwesomeIcon icon={faTree} color="black" size="1x" />
                </p>
                <div
                  className={`${ComfortaaFont.className} text-md md:text-xl mt-1`}
                  style={{
                    color: "black",
                    fontWeight: 800,
                  }}
                >
                  <p>- Phone calls</p>
                  <p>- Arts & crafts</p>
                  <p>- Journaling</p>
                  <p>- Reading</p>
                  <p>- Exercise</p>
                  <p>- Camping</p>
                  <p>- Cooking</p>
                  <p>- Painting</p>
                  <p>- Meditation</p>
                  <p>- Outdoor walks</p>
                  <p>- Yoga</p>
                  <p>- Friends over</p>
                  <p>- Room organization</p>
                  <p>- Play sports</p>
                  <p>- Writing</p>
                </div>
              </div>
            </div>
          </div>

          <PageBottomIcon color="white" />
        </Page>
        {/* <SecondPage>
          <p
            className={`${ComfortaaFont.className} text-3xl md:text-6xl my-2 `}
            style={{
              color: "black",
              fontWeight: 800,
            }}
          >
            Night Before
          </p>

          <p
            className={`${ComfortaaFont.className} text-sm md:text-xl my-1 `}
            style={{
              color: "black",
            }}
          >
            Let friends / family know you will only be responding to phone calls, setup auto-replies
            for messages, print out map directions if you have plans to drive somewhere, print out
            recipes ahead of time. Plan so that not a single phone or computer has to get used.
          </p>

          <p
            className={`${ComfortaaFont.className} text-3xl md:text-6xl my-2 `}
            style={{
              color: "black",
              fontWeight: 800,
            }}
          >
            Day Of
          </p>

          <p
            className={`${ComfortaaFont.className} text-sm md:text-xl my-1 `}
            style={{
              color: "black",
            }}
          >
            Allow yourself to be bored and see where your curiosity takes you that day. Pay
            attention to the habituated patterns to fill empty time with social media and
            doom-scrolling and instead try something new.
          </p>

          <p
            className={`${ComfortaaFont.className} text-3xl md:text-6xl my-2 `}
            style={{
              color: "black",
              fontWeight: 800,
            }}
          >
            Day After
          </p>

          <p
            className={`${ComfortaaFont.className} text-sm md:text-xl my-1 `}
            style={{
              color: "black",
            }}
          >
            Reconnect on missed messages, ease into the world, enjoy the new found space from the
            daily buzz, tell your friends about it.
            <br />
            <br />
            We will start surfacing stories from peoples Unplugged days so feel free to send them to
            unplug.club.stories@gmail.com
          </p>
          <hr
            className="my-4"
            style={{ height: "4px", borderTopColor: "#8B5C004D", width: "100%" }}
          />

          <FontAwesomeIcon
            className="mr-2 fa-fade absolute bottom-6"
            icon={faCircleArrowDown}
            style={{
              bottom: "64px",
            }}
            color="black"
            size="3x"
          />
        </SecondPage> */}
        <LastPage>
          <p
            className={`${ComfortaaFont.className} text-xl md:text-6xl `}
            style={{ marginTop: "2rem" }}
          >
            Why did Unplug happen?
          </p>
          <StyledText
            className={`${ComfortaaFont.className} text-base md:text-lg `}
            style={{ marginTop: "2rem" }}
          >
            We grew tired of unfulfilling days spent doom-scrolling. We grew tired of being so
            tethered to our digital hand-held attention prisons. We grew tired of missing real human
            connection.
            <br />
            <br />
            We wanted to start something different. An occasional, socially responsible period of
            time to unplug and go outside.
            <br />
            <br />
            No, this is not an app. That would defeat the purpose. It is a movement, and we hope you
            try it. Happy Unplugging 🎉
          </StyledText>

          <Image priority src={logo} alt={""} width={100} height={100} className="my-3" />
        </LastPage>
      </Content>
    </>
  );
}
