import { Content, Header } from "@/april28_23/components/layout/layout";
import { LogoText } from "@/april28_23/components/typography/typography";
import { Shantell_Sans } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

const shantellSansFont = Shantell_Sans({ subsets: ["latin"], variable: "--shantell-font" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Unplug</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </Head>
      <Header>
        <div>
          <LogoText className={shantellSansFont.variable}>Unplug</LogoText>
        </div>
      </Header>
      <Content>
        <ul>
          <li>
            <h2 className="text-white text-3xl">
              <Link href="/april28_2023">April 28th, 2013</Link>
            </h2>
          </li>
        </ul>
      </Content>
    </>
  );
}
